### ISSUE TITLE
'getStorage' does not exist in type 'IAuthTokenInterceptorConfig'

### ISSUE THREAD

**Issue by Rawnly** [jetbridge/axios-jwt#52]
Seems like there's a problem with types:

### My test code
```ts
import axios from 'axios'
import { applyAuthTokenInterceptor } from 'axios-jwt'

const api = axios.create()

applyAuthTokenInterceptor(api, { getStorage: () => window.sessionStorage })

```

### Exception
```
src/index.ts(6,34): error TS2345: Argument of type '{ getStorage: () => Storage; }' is not assignable to parameter of type 'IAuthTokenInterceptorConfig'.
  Object literal may only specify known properties, and 'getStorage' does not exist in type 'IAuthTokenInterceptorConfig'.

Error: error occured in dts build
    at Worker.<anonymous> (/Users/federicovitale/Developer/projects/new-proj/node_modules/.pnpm/tsup@6.3.0_typescript@4.8.4/node_modules/tsup/dist/index.js:2181:26)
    at Worker.emit (node:events:527:28)
    at MessagePort.<anonymous> (node:internal/worker:232:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
Error: Failed to compile. Check the logs above.
    at error (/Users/federicovitale/Developer/projects/new-proj/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:198:30)
    at throwPluginError (/Users/federicovitale/Developer/projects/new-proj/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:21718:12)
    at Object.error (/Users/federicovitale/Developer/projects/new-proj/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:22672:20)
    at Object.error (/Users/federicovitale/Developer/projects/new-proj/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:21895:42)
    at Object.transform (/Users/federicovitale/Developer/projects/new-proj/node_modules/.pnpm/tsup@6.3.0_typescript@4.8.4/node_modules/tsup/dist/rollup.js:7217:20)
    at /Users/federicovitale/Developer/projects/new-proj/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:22879:40
[TS-PACKAGE] DTS Build error
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by asadeghi** [comment]
+1

**Comment by revmischa** [comment]
@greenyas

**Comment by revmischa** [comment]
I think you want 
```ts
import axios from "axios";
import { applyAuthTokenInterceptor, getBrowserSessionStorage } from "axios-jwt";

const api = axios.create();

applyAuthTokenInterceptor(api, { getStorage: getBrowserSessionStorage });
```

?

**Comment by Rawnly** [comment]
Yeah, that's what I meant but it didn't compile! Maybe some cache stuff
