### ISSUE TITLE
Uncaught TypeError: (0 , ms_1.default) is not a function

### ISSUE THREAD

**Issue by slushpuppy** [jetbridge/axios-jwt#57]
Appears I am missing the "ms" dependency, installing it doesn't resolve the issue however

Uncaught TypeError: (0 , ms_1.default) is not a function
at authTokenInterceptor (authTokenInterceptor. ts:178:1)
at app lyAuthTokenInterceptor (applyAuthTokenInterceptor.ts:16:1)
at ./src/api/auth.ts (auth.ts:43:1

**Comment by tekyu** [comment]
Same for me, I saw some fixes here https://github.com/vercel/ms/issues/186#issuecomment-1259526771 but nothing works

**Comment by lien-dkseo** [comment]
+1

**Comment by Canoir** [comment]
1+

**Comment by DevWebcorp** [comment]
+1
npm install --save axios-jwt@3.0.0
works for now.

**Comment by MichaelLiss** [comment]
+1
npm install --save axios-jwt@3.0.0
worked for me

**Comment by danilmakarow** [comment]
+1
