### ISSUE TITLE
TypeError when running

### ISSUE THREAD

**Issue by MichaelLiss** [jetbridge/axios-jwt#69]
Added all code per the read me into a REACT (non-type script project)

Started app (NPM run start) and received this:
```
ERROR
(0 , ms_1.default) is not a function
TypeError: (0 , ms_1.default) is not a function
    at authTokenInterceptor (http://localhost:3000/static/js/bundle.js:7344:34)
    at applyAuthTokenInterceptor (http://localhost:3000/static/js/bundle.js:7021:82)
    at ./src/components/axiosApi/axiosApi.js (http://localhost:3000/static/js/bundle.js:338:69)
    at options.factory (http://localhost:3000/static/js/bundle.js:55662:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:55077:33)
    at fn (http://localhost:3000/static/js/bundle.js:55319:21)
    at ./src/components/login/login.js (http://localhost:3000/static/js/bundle.js:468:76)
    at options.factory (http://localhost:3000/static/js/bundle.js:55662:31)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:55077:33)
    at fn (http://localhost:3000/static/js/bundle.js:55319:21)
```

Here is my code:
```
import { applyAuthTokenInterceptor } from 'axios-jwt';
import axios from 'axios';

const BASE_URL = 'http://localhost:5000/api/';

const axiosInstance = axios.create({ baseURL: BASE_URL });

const requestRefresh = (refresh) => {
  // Notice that this is the global axios instance, not the axiosInstance!  <-- important
  return axios.post(`${BASE_URL}/auth/refreshtoken`, { refresh }).then((response) => response.data.token);
};

applyAuthTokenInterceptor(axiosInstance, { requestRefresh }); // Notice that this uses the axiosInstance instance.  <-- important

export default axiosInstance;
```

Dependencies:
```
  "dependencies": {
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^1.6.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.20.1",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
```

**Comment by MichaelLiss** [comment]
+1
npm install --save axios-jwt@3.0.0
worked for me

**Comment by MichaelLiss** [comment]
![image](https://github.com/jetbridge/axios-jwt/assets/39492750/2f2a9a56-27fb-4839-bc90-9a4a59343b0b)

**Comment by MichaelLiss** [comment]
Authorization header is not being set:

![image](https://github.com/jetbridge/axios-jwt/assets/39492750/3fb00cef-6a8f-4570-b7ad-8351cb55ea11)

**Comment by MichaelLiss** [comment]
When I hard code the authorization into the header ... it works:

```
import axios from '../axiosApi/axiosApi';  // where the code is implemented to use this module
...

      let token = 'eyJhbGciOi <snip_for_brevity>'
      const response = await axios.get(url, { headers: {"Authorization" : `Bearer ${token}`} });
```
